{{- $fullName := include "stoat.fullname" . -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stoat.fullname" . }}-env
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  REVOLT__PUSHD__VAPID__PRIVATE_KEY: {{ .Values.global.secret.vapid_key | quote }}
  REVOLT__PUSHD__VAPID__PUBLIC_KEY: {{ .Values.global.secret.vapid_public_key | quote }}
  REVOLT__FILES__ENCRYPTION_KEY: {{ .Values.global.secret.encryption_key | quote }}
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET: {{ .Values.global.secret.livekit_secret | quote }}
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY: {{ .Values.global.secret.livekit_key | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stoat.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  Revolt.toml: |
    # Reference: https://github.com/stoatchat/stoatchat/blob/stable/crates/core/config/Revolt.toml
    # WARNING: This file is managed by Helm. Changes will be overwritten next time the chart is updated.
    production = {{ .Values.stoat.config.production }}

    [database]
    mongodb = {{ .Values.global.subcharts.mongo.connection_url | default (printf "mongodb://%s-mongodb" .Release.Name) | quote }}
    redis = {{ .Values.global.subcharts.redis.connection_url | default (printf "redis://%s-redis-master" .Release.Name) | quote }}

    [rabbit]
    host = {{ .Values.global.subcharts.rabbitmq.host | default (printf "%s-rabbitmq" .Release.Name) | quote }}
    port = {{ .Values.global.subcharts.rabbitmq.port }}
    username = {{ .Values.global.subcharts.rabbitmq.username | quote }}
    password = {{ .Values.global.subcharts.rabbitmq.password | quote }}

    [hosts]
    app = "https://{{ .Values.global.domain }}"
    api = "https://{{ .Values.global.domain }}/api"
    events = "wss://{{ .Values.global.domain }}/ws"
    autumn = "https://{{ .Values.global.domain }}/autumn"
    january = "https://{{ .Values.global.domain }}/january"

    [pushd.vapid]
    private_key = {{ .Values.global.secret.vapid_key | quote }}
    public_key = {{ .Values.global.secret.vapid_public_key | quote }}

    [files]
    encryption_key = {{ .Values.global.secret.encryption_key | quote }}

    [files.s3]
    endpoint = {{ .Values.global.subcharts.garage.connection_url | default (printf "http://%s-garage:3900" .Release.Name) | quote }}
    region = {{ .Values.stoat.config.files.s3.region | quote }}
    default_bucket = {{ .Values.stoat.config.files.s3.default_bucket | quote }}
    access_key_id = {{ .Values.stoat.config.files.s3.access_key_id | quote }}
    secret_access_key = {{ .Values.stoat.config.files.s3.secret_access_key | quote }}
    path_style_buckets = {{ .Values.stoat.config.files.s3.path_style_buckets }}

    [api]

    [api.registration]
    invite_only = {{ .Values.stoat.config.api.registration.invite_only }}

    [api.smtp]
    host = {{ .Values.stoat.config.api.smtp.host | quote }}
    port = {{ .Values.stoat.config.api.smtp.port | quote }}
    username = {{ .Values.stoat.config.api.smtp.username | quote }}
    password = {{ .Values.stoat.config.api.smtp.password | quote }}
    from_address = {{ .Values.stoat.config.api.smtp.from_address | quote }}
    reply_to = {{ .Values.stoat.config.api.smtp.reply_to | quote }}
    use_tls = {{ .Values.stoat.config.api.smtp.use_tls | quote }}

    [api.security.captcha]
    hcaptcha_key = {{ .Values.stoat.config.api.security.captcha.hcaptcha_key | quote }}
    hcaptcha_sitekey = {{ .Values.stoat.config.api.security.captcha.hcaptcha_sitekey | quote }}

    [api.livekit.nodes.worldwide]
    url = "http://{{ $fullName }}-livekit:{{ .Values.global.livekit.port }}"
    lat = 0.0
    lon = 0.0
    key = {{ required ".Values.global.secret.livekit_key is required: openssl rand -hex 6" .Values.global.secret.livekit_key | quote }}
    secret = {{ required ".Values.global.secret.livekit_secret is required: openssl rand -hex 24" .Values.global.secret.livekit_secret | quote }}

    [hosts.livekit]
    worldwide = "wss://{{ .Values.global.domain }}/livekit"

    [features]
    webhooks_enabled = {{ .Values.stoat.config.features.webhooks_enabled }}
    mass_mentions_send_notifications = {{ .Values.stoat.config.features.mass_mentions_send_notifications }}
    mass_mentions_enabled = {{ .Values.stoat.config.features.mass_mentions_enabled }}

    [features.limits.global]
    group_size = {{ .Values.stoat.config.features.limits.global.group_size }}
    message_embeds = {{ .Values.stoat.config.features.limits.global.message_embeds }}
    message_replies = {{ .Values.stoat.config.features.limits.global.message_replies }}
    message_reactions = {{ .Values.stoat.config.features.limits.global.message_reactions }}
    server_emoji = {{ .Values.stoat.config.features.limits.global.server_emoji }}
    server_roles = {{ .Values.stoat.config.features.limits.global.server_roles }}
    server_channels = {{ .Values.stoat.config.features.limits.global.server_channels }}
    new_user_hours = {{ .Values.stoat.config.features.limits.global.new_user_hours }}
    body_limit_size = {{ .Values.stoat.config.features.limits.global.body_limit_size }}

    [features.limits.new_user]
    outgoing_friend_requests = {{ .Values.stoat.config.features.limits.new_user.outgoing_friend_requests }}
    bots = {{ .Values.stoat.config.features.limits.new_user.bots }}
    message_length = {{ .Values.stoat.config.features.limits.new_user.message_length }}
    message_attachments = {{ .Values.stoat.config.features.limits.new_user.message_attachments }}
    servers = {{ .Values.stoat.config.features.limits.new_user.servers }}
    video_resolution = [{{ join ", " .Values.stoat.config.features.limits.new_user.video_resolution }}]
    video_aspect_ratio = [{{ join ", " .Values.stoat.config.features.limits.new_user.video_aspect_ratio }}]

    [features.limits.new_user.file_upload_size_limit]
    attachments = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.attachments }}
    avatars = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.avatars }}
    backgrounds = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.backgrounds }}
    icons = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.icons }}
    banners = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.banners }}
    emojis = {{ .Values.stoat.config.features.limits.new_user.file_upload_size_limit.emojis }}

    [features.limits.default]
    outgoing_friend_requests = {{ .Values.stoat.config.features.limits.default.outgoing_friend_requests }}
    bots = {{ .Values.stoat.config.features.limits.default.bots }}
    message_length = {{ .Values.stoat.config.features.limits.default.message_length }}
    message_attachments = {{ .Values.stoat.config.features.limits.default.message_attachments }}
    servers = {{ .Values.stoat.config.features.limits.default.servers }}
    video_resolution = [{{ join ", " .Values.stoat.config.features.limits.default.video_resolution }}]
    video_aspect_ratio = [{{ join ", " .Values.stoat.config.features.limits.default.video_aspect_ratio }}]


    [features.limits.default.file_upload_size_limit]
    attachments = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.attachments }}
    avatars = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.avatars }}
    backgrounds = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.backgrounds }}
    icons = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.icons }}
    banners = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.banners }}
    emojis = {{ .Values.stoat.config.features.limits.default.file_upload_size_limit.emojis }}

  livekit.yml: |
    rtc:
      use_external_ip: true
      port_range_start: {{ .Values.global.livekit.range_start }}
      port_range_end: {{ .Values.global.livekit.range_end }}
      tcp_port: 7881

    redis:
      address: "{{ .Values.global.subcharts.redis.connection_url | default (printf "%s-redis-master" .Release.Name) }}:6379"

    turn:
      enabled: false

    keys:
      {{ .Values.global.secret.livekit_key }}: {{ .Values.global.secret.livekit_secret }}

    webhook:
      api_key: {{ .Values.global.secret.livekit_key }}
      urls:
        - "http://{{$fullName}}-voice:{{ .Values.global.voice.port }}/worldwide"
{{- /* TODO: Support more config options */ -}}

