apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoat.fullname" . }}-livekit
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: livekit
  {{- with (merge (.Values.global.all.service.annotations | default dict) (.Values.livekit.service.annotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.livekit.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.livekit.port }}
    - name: rtctcp
      targetPort: rtctcp
      port: {{ .Values.global.livekit.rtc_port }}
      protocol: TCP
    {{- range $port := untilStep 50000 50011 1 }}
    - name: live-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "stoat.selectorLabels" . | nindent 4 }}
    stoat-app: livekit
